name: Test and Deploy Contract CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install -y npm
        sudo npm install -g ganache-cli
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with brownie
      run: |
        brownie test --coverage
    - name: Run Deploy to local ganache
      run: |
        brownie run scripts/deploy_token.py
